test깨지는 것 수정
jest.config.js파일 생성하고
preset: "react-native" 설정

/Users/skc/apps/RememberHomes/node_modules/react-native/Libraries/Utilities/warnOnce.js:15
const warnedKeys: {[string]: boolean} = {};
          ^^^^^^^^^^
SyntaxError: Missing initializer in const declaration